version: '2'
  services:
          redis:
                  image: redis
                  networks:
                          - dockerlab
          nodeapp:
                  build: /home/student/docker/devops-docker-nodeapp
                  depends_on: 
                            - redis
                  networks:
                          - dockerlab
                  environment: 
                              - REDIS_HOST=redis
          frontend:
                  build: /home/student/docker/devops-docker-frontend
                  depends_on: 
                            - nodeapp
                  networks:
                          - dockerlab
                  ports:
                        - "8008:80"
  networks:
    dockerlab:
      driver: bridge