version: '2'
services:
          redis:
                  image: localhost:5000/myredis
                  networks:
                          - dockerlab
          nodeapp:
                  image: localhost:5000/mynodeapp
                  depends_on: 
                            - redis
                  networks:
                          - dockerlab
                  environment: 
                              - REDIS_HOST=redis
          frontend:
                  image: localhost:5000/myfrontend
                  depends_on: 
                            - nodeapp
                  networks:
                          - dockerlab
                  ports:
                        - "8008:80"
networks:
        dockerlab:
                  driver: bridge