apiVersion: v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 2
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: edgendadevops/devops-docker-nodeapp:0
      env:
      - name: REDIS_HOST
        value: redis